apiVersion: v1
kind: Service
metadata:
  name: elk-dep
  labels:
    app: elk
spec:
  type: NodePort
  ports:
  - name: kibana
    port: 5601
  - name: logstash 
    port: 5044
  selector:
    app: elk
    tier: elk-dep
